#!/bin/sh
base_dir=`dirname $0`

main=com.xingcloud.dataproxy.membase.test.MembaseTest

classpath=$base_dir/conf
for i in $base_dir/lib/*.jar;
do
 classpath=$classpath:$i
done
for i in $base_dir/dist/*.jar;
do 
 classpath=$classpath:$i
done


java -classpath $classpath $main "$@"
